name: infinite_listview
description: ListView with items that can be scrolled infinitely in both directions.
version: 1.1.0
homepage: https://github.com/fluttercommunity/flutter_infinite_listview
maintainer: Simon Lightfoot (@slightfoot)

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
